model:
  model_path: "models/detector_model.onnx"
  yaml_path: "data.yaml"

params:
  confidence_threshold: 0.3
  prob_threshold: 0.3
  nms_threshold: 0.50
  input_width: 640
  input_height: 640

inference:
  input_image: "data/samples/ROI_detector/detection_result.png"
  output_dir: "output/"
