model:
  model_path: "models/detector_model.onnx"
  yaml_path: "data.yaml"
  classifier_model_path: "models/classifier_mdl.pth"
  classifier_labels_path: "src/classification/classifier_labels.yaml"

params:
  confidence_threshold: 0.269 # based on f1-confidence curve from yolo training 
  prob_threshold: 0.20
  nms_threshold: 0.70
  input_width: 640
  input_height: 640

inference:
  input_image: "data/samples/ROI_detector/eczema_0.webp"
  output_dir: "output/"

classifier_constants:
  imagenet_mean: [0.485, 0.456, 0.406]
  imagenet_std: [0.229, 0.224, 0.225]
